Task 1
Otus-DevOps-22-08/students pull request #13
Opened 2022-09-09 21:07 UTC by drassadnikov

Task 1 - drassadnikov

2022-09-09 21:34 UTC, drassadnikov commented
Сделан pull request - drassadnikov

2022-09-11 15:34 UTC, mrgreyves requested changes
Эммм, нужно добавить новый файл, а не переименовывать существующий
Вам стоит немного передалать дз, много времени на это точно не уйдет
ДЗ возвращаю на доработку

2022-09-11 15:45 UTC, mrgreyves commented
Пожалуй закрою ваш пуллреквест
Что к вам точно пришло оповещение =)

2022-09-11 15:45 UTC, closed without merging

2022-09-12 06:40 UTC, drassadnikov commented
Здравствуйте. Сделал новый pull request:
https://github.com/Otus-DevOps-22-08/students/pull/25